export const CATEGORIES = [
  { id: 1, name: 'Молочні продукти', color: '#4AB3D6' },
  { id: 2, name: 'Мʼясо', color: '#E74C3C' },
  { id: 3, name: 'Риба', color: '#2E86C1' },
  { id: 4, name: 'Овочі', color: '#27AE60' },
  { id: 5, name: 'Фрукти', color: '#F4D03F' },
  { id: 6, name: 'Крупи', color: '#D7B899' },
  { id: 7, name: 'Хлібобулочні', color: '#C39A6B' },
  { id: 8, name: 'Заморожені', color: '#85C1E9' },
  { id: 9, name: 'Напої', color: '#8E44AD' },
  { id: 10, name: 'Солодощі', color: '#F1948A' },
  { id: 11, name: 'Соуси', color: '#F39C12' },
  { id: 12, name: 'Консерви', color: '#7F8C8D' },
  { id: 13, name: 'Горіхи', color: '#8B5E3C' },
  { id: 14, name: 'Яйця', color: '#F8E8C6' },
  { id: 15, name: 'Готові страви', color: '#D35400' },
  { id: 16, name: 'Інше', color: '#D5D8DC' },
];
